### ISSUE TITLE
在配置参数中开启Switch of log web console后，磁盘节点和内存节点的服务不正常

### ISSUE THREAD

**Issue by mayuhope** [QingCloudAppcenter/RabbitMQ#12]
测试步骤：
1.创建完一个集群，类型为生产环境；
2.创建完后待所有节点服务都启动后，进入配置参数，修改属性，进行如下设置：

Switch of log web console | true |
Username of log web console | admin 
Password of log web console | ******

保存，确认；

3.稍后查看集群节点服务状态，发现磁盘节点和内存节点的服务均不正常；
![image](https://user-images.githubusercontent.com/7677050/85286307-f7129000-b4c4-11ea-80bb-8f22a0401c15.png)

**Comment by spwangxp** [comment]
已重提镜像

**Comment by mayuhope** [comment]
后来测试正常
